### ISSUE TITLE
Generated SD card does not boot, kernel panic

### ISSUE THREAD

**Issue by a-v-s** [sehraf/riscv-arch-image-builder#17]
I have run the scripts [1_compile.sh](https://github.com/sehraf/riscv-arch-image-builder/blob/main/1_compile.sh) and [2_create_sd.sh](https://github.com/sehraf/riscv-arch-image-builder/blob/main/2_create_sd.sh).
When I try to boot the resulting image, it fails to boot. The kernel loads, mounts the SD card and starts the init process. However, the init process then crashes.

This occurs on both Mango Pi and Nezha boards. I have attached the boot logs. 

[mango.txt](https://github.com/sehraf/riscv-arch-image-builder/files/9795432/mango.txt)
[nezha.txt](https://github.com/sehraf/riscv-arch-image-builder/files/9795433/nezha.txt)

**Comment by sehraf** [comment]
Since it's reaching user space, can you update the rootfs (e.g. by chroot)? 
Beside this, there isn't much i can do, (kernel) booting itself works fine.

**Comment by a-v-s** [comment]
After chrooting into the image and updating the packages, the problem still remains unchanged. 
```
[    4.161561] Unable to handle kernel paging request at virtual address ffffffffdfffffff
```

Running bash as init appears to work. So yes, the kernel works. But there seems to be some incompatibility with the systemd from felixcat's repo.

**Comment by sehraf** [comment]
can it be a SD card issue? It's working on my lichee rv and mango pi (with an up to date arch)

**Comment by a-v-s** [comment]
A different SD card gives the same results. 

I've tried different power supplies. The Nezha board booted to the login promp, while the Mango still failed the same as before. When I tried the Nezha again, it started failing again. I will do some more testing. 

But just to confirm, the same image should work on all the boards, without adjusted device tree?

**Comment by sehraf** [comment]
I stand corrected (partly).

So using a freshly build image/sd card i get the same error on my mango pi, but it's working fine on the lichee rv.
But using my existing arch installation, it's working fine on both systems. :confused: 
Both run the same kernel 5.18.0-rc1 - they might have different u-boot versions (once initially created, i've updated the system with pacman and (manually) updated the kernel on my existing installation).

---

> But just to confirm, the same image should work on all the boards, without adjusted device tree?

This is a tricky question and might be the culprit here.
_Usually_ you _cannot_ switch SBC due to differences. In the case of the mango pi and lichee rv, they are very similar thus is it actually working (in my case) (or not in your case :man_shrugging: ).
My guess is that the bootloader / dtb / w/e is different and causing the problems. For the Nezha you could try to use [sun20i-d1-nezha.dts](https://github.com/smaeul/u-boot/blob/d1-wip/arch/riscv/dts/sun20i-d1-nezha.dts) in https://github.com/sehraf/riscv-arch-image-builder/blob/544cc25d8faf638e58f77538d510cddf20a99c77/1_compile.sh#L88

**Comment by a-v-s** [comment]
My Mango Pi is a revision 1.3 board with 1 GiB RAM.

Something goes wrong when trying to get that device tree in. 
[log.txt](https://github.com/sehraf/riscv-arch-image-builder/files/9833064/log.txt)

I changed the compile script as follows (.txt to make github happy) 
[1_compile.sh.txt](https://github.com/sehraf/riscv-arch-image-builder/files/9833079/1_compile.sh.txt)

I don't have much time right now to look into it. I will look into what is going on next week.
