### ISSUE TITLE
Images built after "update kernel" does not work

### ISSUE THREAD

**Issue by Vinibo** [sehraf/riscv-arch-image-builder#23]
Hi, 

First of all, thank you for your work, porting our favorite OS on the small Risc-V board!

I had trouble creating a working image in the past couple days. I also notice that Github actions shows that before the commit "update kernel", images had a size of > 300mb. After this commit, images are less than 2mb.

Writing the newer images on SD cards shows no partitions.

Thank you!

**Comment by sehraf** [comment]
Hi!

> porting our favorite OS

Thanks but i'm not porting arch, Felix is doing it https://archriscv.felixc.at/ :wink: 

> After this commit, images are less than 2mb.

This looks definitely fishy. Thanks for reporting!
Let's see if c72f8b0e36b1f1f3cd33d545d1ea6444f6168f78 fixes the issue.

> Writing the newer images on SD cards shows no partitions.

Did you tell your kernel to reload the partitions? Otherwise, unplug the SD card and plug it back in. Do the partitions then show up?

**Comment by sehraf** [comment]
the ci artifact is fixed by 29b4576dea6775dd6ae1df4ebe192661556f27b2
